package model;
// Generated 26.Ağu.2019 09:08:06 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "procategory")
public class Procategory implements java.io.Serializable {

	private Integer ctid;
	private String ctname;

	public Procategory() {
	}

	public Procategory(String ctname) {
		this.ctname = ctname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ctid", unique = true, nullable = false)
	public Integer getCtid() {
		return this.ctid;
	}

	public void setCtid(Integer ctid) {
		this.ctid = ctid;
	}

	@Column(name = "ctname", nullable = false)
	public String getCtname() {
		return this.ctname;
	}

	public void setCtname(String ctname) {
		this.ctname = ctname;
	}	

}