package model;
// Generated 26.Ağu.2019 09:08:06 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private Integer pid;
	private String ptitle;
	private String pphoto;
	private BigDecimal pprice;
	private Integer pcategory;
	private Integer pstatu;
	private String pdetail;

	public Product() {
	}

	public Product(String ptitle, String pphoto, BigDecimal pprice, Integer pcategory, Integer pstatu, String pdetail) {
		this.ptitle = ptitle;
		this.pphoto = pphoto;
		this.pprice = pprice;
		this.pcategory = pcategory;
		this.pstatu = pstatu;
		this.pdetail = pdetail;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pid", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "ptitle", nullable = false)
	public String getPtitle() {
		return this.ptitle;
	}

	public void setPtitle(String ptitle) {
		this.ptitle = ptitle;
	}

	@Column(name = "pphoto", nullable = false, length = 500)
	public String getPphoto() {
		return this.pphoto;
	}

	public void setPphoto(String pphoto) {
		this.pphoto = pphoto;
	}

	@Column(name = "pprice", nullable = false, precision = 10)
	public BigDecimal getPprice() {
		return this.pprice;
	}

	public void setPprice(BigDecimal pprice) {
		this.pprice = pprice;
	}
	
	@Column(name = "pcategory", nullable = false)
	public Integer getPcategory() {
		return this.pcategory;
	}

	public void setPcategory(Integer pcategory) {
		this.pcategory = pcategory;
	}
	
	@Column(name = "pstatu", nullable = false)
	public Integer getPstatu() {
		return this.pstatu;
	}

	public void setPstatu(Integer pstatu) {
		this.pstatu = pstatu;
	}
	
	@Column(name = "pdetail", nullable = false)
	public String getPdetail() {
		return this.pdetail;
	}

	public void setPdetail(String pdetail) {
		this.pdetail = pdetail;
	}

}
