package model;
// Generated 26.Ağu.2019 09:08:06 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private String umail;
	private String upassword;

	public User() {
	}

	public User(String uname, String umail, String upassword) {
		this.uname = uname;
		this.umail = umail;
		this.upassword = upassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "uname", nullable = false)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "umail", nullable = false)
	public String getUmail() {
		return this.umail;
	}

	public void setUmail(String umail) {
		this.umail = umail;
	}

	@Column(name = "upassword", nullable = false)
	public String getUpassword() {
		return this.upassword;
	}

	public void setUpassword(String upassword ) {
		this.upassword = upassword ;
	}
	

}
